### ISSUE TITLE
Data will not sync

### ISSUE THREAD

**Issue by redstarnyc** [sheibeck/fiveparsecscompanion#51] opened 2021-12-21 16:12 UTC
I use the site on my windows 11 machine using google chrome.  The data is persistent on my windows machine, but does not sync across any of my other devices - android phone, or chromebook.

I've tried clearing the cache as well as refreshing the browsers multiple times.

**Comment by sheibeck** [comment] 2022-01-03 21:27
Quick update, there's definitely an issue here. I'm experiencing the same problem. When I clear my local storage on chrome in android, I lose all my data. This isn't the case for desktop where everything appears to be working just fine. Still not sure of the cause, but will be working on it.

Oddly enough, on desktop I am seeing 401 auth error in amazon graphql queries. Not sure if this is related. 

I'll update when I know more.

**Comment by sheibeck** [comment] 2022-01-04 04:29
Turns out this was a huge mess that started with an update at AWS. It's a long, sordid story, but alas, I believe this is fixed now. I'm seeing data sync across devices once again. Unfortunately, I'm not exactly sure when this issue started, so I'm not sure how many times it will keep trying to sync data before it gives up.

A few of my tests were failing to sync, but I was actually deleting my entire local storage instance in my tests, which probably killed my ids that were trying to sync. So, as long as no did that, I think this will start working again.

Let me know if you see your data start to sync across devices now or if not, let me know that, too. Thanks again for taking the time to report his issue. Sorry for any inconvenience.

**Closed by sheibeck** 2022-01-04 04:29 UTC
